---
title: "Protocolo"
bibliography: Referencias.bib
csl: ama.csl
---
**Fecha de última actualización:** `r Sys.Date()`

***

\ 

Esta sección contiene el Informe Final del "Programa de Diagnóstico y Tratamiento Precoz del Cáncer de Cuello Uterino", gestionado por la Dirección de Investigación & Divulgación Científica de la Universidad del Norte. El Programa se ejecutó dentro del *Programa Paraguayo para el Desarrollo de la Ciencia y la Tecnología* (PROCIENCIA), Proyecto 14-INV-458, con fondos adjudicados por el *Consejo Nacional de Ciencia y Tecnología* (CONACYT) de la República del Paraguay según Resolución Nº 085/2015.

***

## Equipo de investigadores
El Investigador Principal del proyecto fue el __Prof. Dr. Alcides Chaux__, Director de Investigación & Divulgación Científica de la Universidad del Norte. El Investigador Principal estuvo a cargo del diseño y supervisión del proyecto, contratación del personal técnico y laboratorial, supervisión del proceso de recolección y análisis de datos, revisión del diagnóstico citológico y anatomopatológico, y supervisión de la redacción de informes de investigación y documentos relacionados.

La __Bioq. Anahí Martínez__ fue la Asistente de Investigación del Proyecto. La Asistente estuvo a cargo del procesamiento de las muestras citológicas y tisulares, y de la recolección y análisis de datos y redacción de informes de investigación y documentos relacionados.

La __Dra. Cynthia Paredes__ fue la especialista en Ginecología y Anatomía Patológica. La Especialista estuvo a cargo del examen físico y ginecológico de la paciente, de la evaluación colposcópica, y de la toma y diagnóstico morfológico de muestras citológicas y tisulares de cuello uterino. La Especialista estuvo a cargo también de interpretar los resultados obtenidos en el Programa a la paciente y de brindarle las indicaciones necesarias.

***

## Objetivos del proyecto
__Objetivos principales:__ Los objetivos principales de este proyecto se agruparon en 2 ejes:

- Detectar lesiones preneoplásicas y neoplásicas precoces del cuello uterino en mujeres en edad reproductiva.
- Ofrecer tratamiento precoz en aquellos casos que así lo ameriten (i.e., lesiones preneoplásicas de alto grado) y derivar a centros de mayor complejidad a aquellas pacientes que requieran tratamientos más complejos (v.g., aquellas pacientes con lesiones neoplásicas invasivas). A largo plazo, el objetivo principal del programa es reducir la incidencia y mortalidad del cáncer de cuello uterino.

__Objetivos específicos:__ Los objetivos específicos de este proyecto se agruparon en 3 ejes:

- Detectar lesiones preneoplásicas y neoplásicas precoces del cuello uterino utilizando la técnica de citología ginecológica de Papanicolaou, mediante evaluación colposcópica.
- Confirmar el diagnóstico de la citología ginecológica mediante la biopsia de cuello uterino + legrado endocervical en los casos apropiados.
- Ofrecer el tratamiento apropiado para las lesiones preneoplásicas, ya sea seguimiento o LEEP, y derivar a otros centros hospitalarios aquellas pacientes que requieran tratamientos más complejos, ya con el diagnóstico anatomopatológico hecho.

***

## Antecedentes
El cáncer de cuello uterino constituye uno de los tumores malignos más frecuentes en las mujeres, estando su incidencia y mortalidad directamente relacionadas con la implementación exitosa de programas de detección precoz de lesiones preneoplásicas. Las técnicas de diagnóstico precoz ya han sido establecidas y están en uso a nivel mundial (en mayor o menor medida) desde hace más de 50 años, incluyendo principalmente la realización de la citología exfoliativa del cuello uterino, según la técnica de Papanicoloau.

Sin embargo, el cáncer de cuello uterino sigue siendo la principal causa de muerte por cáncer en mujeres paraguayas. A diferencia de otros países, en los que el número de casos de cáncer de cuello uterino ha disminuido con el tiempo, en el nuestro se mantiene. Las razones de esto están relacionadas con la efectividad de los programas de prevención, y específicamente con la implementación del diagnóstico por citología exfoliativa del cuello uterino en todas las mujeres en edad reproductiva a nivel masivo. 
El fallo en la implementación generalizada del Papanicolaou y faltas de control de calidad adecuados explicarían el por qué estos programas de prevención no han resultado tan efectivos en nuestro país. El Ministerio de Salud Pública y Bienestar Social cuenta con un programa de prevención del cáncer de cuello uterino, pero el servicio ofrecido es subóptimo, demorándose el diagnóstico muchas veces semanas o incluso meses.

Esto hace que los diagnósticos no lleguen a manos de los profesionales médicos a tiempo, con lo cual no pueden instaurarse medidas de control apropiadas. Además, el costo de diagnóstico de confirmación anatomopatológico (i.e., biopsia de cuello uterino + legrado endocervical) corre muchas veces a costa del paciente, representando esto una importante limitación para la confirmación del diagnóstico citológico.

Finalmente, muchas lesiones preneoplásicas de cuello uterino pueden tratarse mediante la técnica del LEEP (por *Loop Electrosurgical Excision Procedure*, procedimiento de excisión electroquirúrgica por asa) pero los costos de dichos tratamientos hacen que los pacientes de escasos recursos no puedan acceder a los mismos. Todas estas variables actuando en conjunto conducen a un fallo en la implementación exitosa del programa de prevención del cáncer de cuello uterino a nivel público.

Con el fin de contribuir a la disminución del número de muertes por cáncer de cuello uterino, lanzamos el "Programa de Prevención y Diagnóstico Precoz del Cáncer de Cuello Uterino" de la Universidad del Norte, mediante el cual se ofrecerá a la población general el diagnóstico de Papanicolaou gratuitamente. Estos diagnósticos se realizarán de manera rápida y por profesionales altamente entrenados, con estrictos controles de calidad.

El "Programa de Prevención y Diagnóstico Precoz del Cáncer de Cuello Uterino" ofrecerá también de manera gratuita la confirmación diagnóstica mediante la biopsia de cuello uterino + legrado endocervical, por lo que aquellas pacientes que presenten lesiones preneoplásicas en la citología podrán ser categorizadas apropiadamente en aquellas que requieren seguimiento únicamente o en aquellas que requieren una intervención quirúrgica.

Dentro del último grupo, el "Programa de Prevención y Diagnóstico Precoz del Cáncer de Cuello Uterino" ofrecerá de manera gratuita la realización del tratamiento por LEEP, en el caso de que corresponda al tratamiento más apropiado, o derivará a la paciente a un centro médico de mayor complejidad, con toda su historia clínica y diagnósticos, para un mejor tratamiento.

***

## Marco teórico
El cáncer de cuello uterino puede considerarse como uno de los pocos tumores malignos del Siglo XXI que puede ser prevenido a través de vacunación y/o detección precoz apropiadas. Sin embargo, continúa siendo un problema mayor en muchas sociedades, principalmente en aquellas regiones del mundo con recursos económicos limitados. Basándose en tasas crudas de incidencia, el cáncer de cuello uterino es el 3º tipo más frecuente de cáncer en mujeres alrededor del mundo, después del cáncer de mama y el colorrectal.

La OMS estima que aparecen 528.000 nuevos casos cada año, siendo la 4º causa más frecuente de muerte por cáncer (266.000 muertes en 2012) en mujeres a nivel mundial. La mayoría de los nuevos casos (85%) aparece en regiones geográficas menos desarrolladas. Sin embargo, si se utilizan tasas de incidencia ajustadas por edad, el cáncer de cuello uterino se convierte en el 2º tipo de cáncer más frecuente en mujeres a nivel mundial[@Ferlay2010] y se ubica 3º en mortalidad después del cáncer de mama y de pulmón.[@Ferlay2010; @Arbyn2011]

Dentro de todos los tumores femeninos, el cáncer de cuello uterino es el más frecuente en África Sub-Sahariana, Asia Sur Central y Melanesia, ocupa el 2º lugar en América Latina y el Caribe, y el 3º lugar en Europa Central y Este y en el Medio Oriente y África Norte. De manera lamentable, no existen datos actuales acerca de la incidencia del cáncer de cuello uterino en el Paraguay,[@Forman2014] lo que implica un fallo importante a nivel del Ministerio de Salud Pública y Bienestar Social. Sin embargo, estimaciones hechas por la OMS indican que el cáncer de cuello uterino es el cáncer más frecuente en mujeres paraguayas en edad reproductiva.[@Ferlay2010]

El cáncer de cuello uterino afecta primariamente a mujeres jóvenes, con consecuencias desastrosas no sólo a nivel individual, sino también socialmente en términos de crianza de hijos y fuerza laboral. Este hecho resulta en más años de vida perdidos proporcionalmente, comparados con otros tipos de cánceres. Más aún, la carga de muertes prematuras, contabilizadas como años de vida perdidos, es inversamente proporcional al ingreso.

El cáncer de cuello uterino es la principal causa de años de vida perdidos debido al cáncer en países con bajos ingresos, dando cuenta de 3.4 millones de años de vida perdidos a nivel mundial. Es además responsable del 22% de las muertes prematuras en mujeres en edad reproductiva debidas al cáncer.[@Mathers2008] Categóricamente, el cáncer de cuello uterino es una enfermedad que surge de la desigualdad social, un paradigma de la disparidad sanitaria mundial.[@Varughese2010]

Las marcadas disminuciones en incidencia y mortalidad observadas en la mayoría de los países desarrollados después de la introducción de programas bien organizados de diagnóstico precoz no han sido observadas en América Latina. Sólo algunos pocos países han sido capaces de implementar la infraestructura comprehensiva necesaria para proveer cobertura amplia con servicios diagnósticos y terapéuticos de alta calidad, con la suficiente sustentabilidad para obtener los niveles de reducción en la carga del cáncer de cuello uterino observados en los países más favorecidos.

En el Paraguay, debido a la falta de datos y un programa efectivo de diagnóstico precoz, no es ni siquiera posible estimar el impacto que dichas medidas pudieran tener. Estos hallazgos indican la necesidad de implementar medidas disponibles actualmente para disminuir la incidencia y mortalidad del cáncer de cuello uterino, principalmente programas de detección y tratamiento precoz de la enfermedad.

***

## Plan de trabajo
Se espera reclutar 1000 pacientes para evaluación ginecológica, colposcópica y citológica. Se estima que 80 de estas pacientes presentarán alteraciones que ameriten una biopsia de cuello uterino + legrado endocervical. De estas 80 pacientes, se estima que 50 necesitarán de un LEEP basándose en los resultados de la biopsia + legrado.

El proyecto estará dividido en 4 fases: promoción, recolección de datos, análisis de datos, y divulgación de resultados.

1) __Promoción:__ El Programa se iniciará con la promoción del mismo a través de medios de difusión masiva de la información, ya sean impresos (v.g., diarios, revistas), radiales o digitales (v.g., redes sociales). El objetivo de esta promoción será el de informar suficientemente a la comunidad de la disponibilidad de los servicios ofrecidos por el Programa, enfatizando la gratuidad del mismo. La promoción del Programa continuará a lo largo de la fase de recolección de datos.

2) __Recolección de datos:__ La fase de recolección de datos constará de hasta 7 etapas, y tendrá como objetivo recolectar los datos necesarios para satisfacer los objetivos de Programa. Las etapas de esta fase se describen a continuación.

    - **Primera consulta ginecológica y toma de muestra citológica.** La recolección de datos se iniciará con una consulta ginecológica, llevada a cabo por la Especialista que procederá a la entrevista médica y el examen físico relevante. En esta primera consulta se procederá al examen colposcópico y toma de muestra de citología ginecológica. Los detalles del examen colposcópico se consignarán en un informe específico. Este informe colposcópico se incluirá en la Historia Clínica de la paciente, que incluirá toda la documentación generada de aquí en adelante. La consulta ginecológica se llevará a cabo en el Policlínico UniNorte, el que cuenta con un Consultorio de Ginecología debidamente equipado. Se establecerá un horario específico para las consultas y tomas de muestras y una Secretaría de Admisión dentro del Policlínico UniNorte.
    - **Diagnóstico citológico.** La muestra citológica será teñida siguiendo la técnica de Papanicolaou en un área apropiada habilitada para el efecto dentro del edificio del Policlínico UniNorte. La Asistente de Investigación y los Auxiliares de Investigación podrán participar del procesamiento y tinción de las muestras citológicas. Posteriormente, la Especialista examinará y clasificará la muestra citológica siguiendo la última clasificación de Bethesda para lesiones epiteliales de cuello uterino.
    - **Segunda consulta ginecológica y evolución del caso.** Una vez hecho el diagnóstico citológico la paciente consultará por segunda vez para recibir los resultados del informe diagnóstico. En el caso de que la muestra citológica resulte dentro de límites normales se le indicará a la paciente que la siguiente consulta deberá ser dentro de 12 meses. En el caso de que el informe diagnóstico indique la sospecha de una lesión preneoplásica ("citología positiva") se procederá a la biopsia de cuello uterino + legrado endocervical, ya sea en esa misma consulta o en una nueva consulta.
    - **Biopsia de cuello uterino + legrado endocervical.** El especialista médico procederá a la biopsia de cuello uterino + legrado endocervical. Las muestras serán procesadas por la Especialista para la obtención de las láminas histológicas correspondientes al procesamiento del material. Las láminas histológicas serán evaluadas por la Especialista y los resultados discutidos con otros miembros del equipo de investigadores, de ser apropiado. Una vez finalizada la evaluación de las láminas histológicas se procederá a la redacción del informe anatomopatológico.
    - **Tercera consulta ginecológica y evolución del caso.** Una vez hecho el diagnóstico anatomopatológico las pacientes con una citología positiva consultarán por tercera vez. En dicha consulta se informará a la paciente de los resultados de la biopsia + legrado, y se establecerá la conducta a seguir. En el caso de que el diagnóstico anatomopatológico indique una lesión preneoplásica se ofrecerá a la paciente el tratamiento por LEEP. En el caso de que el informe anatomopatológico indique una lesión neoplásica se derivará a la paciente a un centro médico de mayor complejidad, entregándole a la paciente una copia de toda su Historia Clínica.
    - **Tratamiento por LEEP.** En el caso de que resulte apropiado según el diagnóstico anatomopatológico y la paciente opte por este tratamiento, se procederá a la excisión del cuello uterino mediante LEEP. El espécimen quirúrgico del LEEP será procesado para fijación en formol al 10% en un área apropiada habilitada para el efecto dentro del edificio del Policlínico UniNorte. Las muestras serán procesadas por la Especialista para la obtención de las láminas histológicas correspondientes al procesamiento del material. Las láminas histológicas serán evaluada por la Especialista y los resultados discutidos con otros miembros del equipo de investigadores, de ser apropiado. Una vez finalizada la evaluación de las láminas histológicas se procederá a la redacción del informe anatomopatológico.
    - **Cuarta consulta ginecológica y evolución del caso.** Una vez hecho el diagnóstico anatomopatológico del especimen quirúgico de LEEP las pacientes que optaron por este tratamiento consultarán nuevamente. En esta consulta la Especialista discutirá con la paciente el protocolo a seguir, así como agendará las consultas subsiguientes de acuerdo a las características del caso.

3) __Análisis de datos:__ En la fase de análisis de datos se procederá a la creación de una base de datos conteniendo toda la información recolectada. El análisis de los datos se realizará con R sobre la base de datos prolija. Todos los resultados serán almacenados en un repositorio online internacional.

4) __Divulgación de datos:__ En la fase de divulgación de datos se procederá a la redacción del informe de investigación, el que se utilizará para generar materiales informativos para la comunidad académica y el público en general. También se redactará al menos un artículo de investigación, el que será enviado para publicación en una revista científica.

***

## Relevancia
**Relevancia social:** Este "Programa de Prevención y Diagnóstico Precoz del Cáncer de Cuello Uterino" permitirá que pacientes de escasos recursos económicos puedan recibir un diagnóstico oportuno y gratuito, incluyendo desde el diagnóstico citológico hasta el tratamiento de lesiones preneoplásicas. Socialmente, este Programa permitirá a largo plazo la reducción de la incidencia y mortalidad del cáncer de cuello uterino, enfocándose en la población más susceptible y desprotegida. Este programa Pretende además paliar todas las deficiencias surgidas en programas similares que son ejecutados por entidades públicas. De esta manera, se obtendrá una mayor inclusión social de las pacientes en edad reproductiva en programas de prevención del cáncer de cuello uterino.

**Relevancia científica:** Este "Programa de Prevención y Diagnóstico Precoz del Cáncer de Cuello Uterino" permitirá el establecimiento de una línea concreta de investigación en cáncer de cuello uterino desde una Universidad privada. Este Programa permitirá asimismo el fortalecimiento en las capacidades de investigación y la gestión de conocimientos relevantes, ayudando a proteger, promocionar y restaurar la salud humana enfocándose en el diagnóstico precoz y la prevención. Finalmente, el establecimiento de esta línea de investigación abrirá oportunidades para líneas de investigación paralelas que puedan utilizar el material generado (v.g., datos clínicos, muestras tisulares) para evaluar nuevas preguntas de investigación (v.g., factores pronósticos moleculares en cánceres del cuello uterino). 

**Relevancia contemporánea:** Este "Programa de Prevención y Diagnóstico Precoz del Cáncer de Cuello Uterino" presenta trascendencia contemporánea al enfocarse en la implementación de medidas preventivas y de diagnóstico precoz del cáncer de cuello uterino, uno de los tumores malignos más frecuentes en las sociedades actuales. Al enfocarse en el aspecto preventivo y de diagnóstico precoz este Programa se alinea con la tendencia actual de poner el énfasis en la prevención y el diagnóstico precoz, lo que permitirá una asistencia sanitaria comunitaria más costo-efectiva.

***

## Estrategia de divulgación
El "Programa de Prevención y Diagnóstico Precoz del Cáncer de Cuello Uterino" permitirá evaluar independientemente los datos epidemiológicos acerca de la enfermedad proveídos por entidades gubernamentales y organizaciones internacionales. Mediante este Programa se generará información suficiente sobre una cohorte de 1000 pacientes, cohorte que podrá ser seguida a mediano y largo plazo, con lo que se podrán obtener datos más precisos acerca de las características de la enfermedad en la población paraguaya. También permitirá crear conciencia a nivel social de la importancia de la detección precoz de las lesiones preneoplásicas que podrían evolucionar a un cáncer de cuello uterino.

**Estrategia de transferencia de conocimientos a los beneficiarios involucrados:** Mediante el "Programa de Prevención y Diagnóstico Precoz del Cáncer de Cuello Uterino" las pacientes recibirán información apropiada y científicamente correcta acerca de la importancia y utilidad de la citología ginecológica, aprenderán a interpretar correctamente los resultados de la citología ginecológica, y comprenderán la importancia de la confirmación diagnóstica mediante la biopsia de cuello uterino. Finalmente, comprenderán las opciones de tratamiento que existen para las lesiones prenoeplásicas del cuello uterino. El especialista médico y el equipo de investigadores proveerán de materiales informativos, según conveniencia.

**Plan de divulgación de resultados a la sociedad:** Los resultados del "Programa de Prevención y Diagnóstico Precoz del Cáncer de Cuello Uterino" serán divulgados mediante canales académicos y no académicos. En el ámbito académico, los resultados se divulgarán mediante Congresos y Simposios, ya sea organizados por la Universidad del Norte u otras instituciones académicas, y el reporte de investigación final será publicado en una revista científica. En el ámbito no académico, estos resultados se divulgarán al público en general mediante entrevistas radiales y televisivas, además de medios impresos y digitales, y redes sociales.

***

## Referencias
